# Generated by Django 2.0.7 on 2018-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('caption', models.CharField(default='', max_length=255)),
                ('desc', models.TextField()),
                ('page_name', models.CharField(max_length=30)),
                ('sm_icon', models.URLField(default='')),
                ('lg_icon', models.URLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
