# Generated by Django 2.0.7 on 2018-07-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0002_auto_20180713_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('sm_icon', models.URLField(blank=True, default='')),
                ('lg_icon', models.URLField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bios', to='rp.Character')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bios', to='rp.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
