# Generated by Django 2.0.7 on 2018-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0009_remove_character_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='verses',
            field=models.ManyToManyField(related_name='characters', through='rp.Bio', to='rp.Verse'),
        ),
    ]
