# Generated by Django 2.0.7 on 2018-07-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0010_character_verses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='caption',
            new_name='_caption',
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='desc',
            new_name='_desc',
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='lg_icon',
            new_name='_lg_icon',
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='sm_icon',
            new_name='_sm_icon',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='display_name',
        ),
        migrations.AddField(
            model_name='bio',
            name='_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
