# Generated by Django 2.0.7 on 2018-07-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0012_auto_20180718_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='character',
            new_name='bio_char',
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='verse',
            new_name='bio_verse',
        ),
    ]
