# Generated by Django 2.0.7 on 2018-07-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0013_auto_20180718_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactertrait',
            old_name='character',
            new_name='char',
        ),
    ]
