# Generated by Django 2.0.7 on 2018-07-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0015_auto_20180718_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='rp.Character'),
            preserve_default=False,
        ),
    ]
