# Generated by Django 2.0.7 on 2018-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0016_auto_20180719_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
