# Generated by Django 2.0.7 on 2018-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0017_auto_20180719_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.FileField(upload_to='')),
                ('fc', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
