# Generated by Django 2.0.7 on 2018-07-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0018_fcimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FcImg',
            new_name='Image',
        ),
    ]
