# Generated by Django 2.0.7 on 2018-07-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0020_auto_20180725_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
