# Generated by Django 2.0.7 on 2018-07-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0026_auto_20180725_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biotrait',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='biotrait',
            name='trait_ptr',
        ),
        migrations.RemoveField(
            model_name='charactertrait',
            name='char',
        ),
        migrations.RemoveField(
            model_name='charactertrait',
            name='trait_ptr',
        ),
        migrations.RemoveField(
            model_name='versetrait',
            name='trait_ptr',
        ),
        migrations.RemoveField(
            model_name='versetrait',
            name='verse',
        ),
        migrations.AlterField(
            model_name='about',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abouts', to='rp.AboutCategory'),
        ),
        migrations.AlterField(
            model_name='about',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abouts', to='rp.Character'),
        ),
        migrations.AlterField(
            model_name='about',
            name='verse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abouts', to='rp.Verse'),
        ),
        migrations.DeleteModel(
            name='BioTrait',
        ),
        migrations.DeleteModel(
            name='CharacterTrait',
        ),
        migrations.DeleteModel(
            name='Trait',
        ),
        migrations.DeleteModel(
            name='VerseTrait',
        ),
    ]
