# Generated by Django 2.0.7 on 2018-07-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0027_auto_20180725_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traits', to='rp.Character')),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traits', to='rp.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='category',
        ),
        migrations.RemoveField(
            model_name='about',
            name='character',
        ),
        migrations.RemoveField(
            model_name='about',
            name='verse',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutCategory',
        ),
    ]
