# Generated by Django 2.0.7 on 2018-07-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0030_auto_20180731_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rp.Script'),
        ),
    ]
