# Generated by Django 2.0.7 on 2018-08-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0031_auto_20180731_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
