# Generated by Django 2.0.7 on 2018-08-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0032_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['display_name']},
        ),
    ]
