# Generated by Django 2.0.7 on 2018-08-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0036_hc_headcanon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='threads', to='rp.Verse'),
        ),
    ]
