# Generated by Django 2.0.7 on 2018-07-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('franchise', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='lg_icon',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='sm_icon',
            field=models.URLField(blank=True, default=''),
        ),
    ]
