# Generated by Django 2.0.7 on 2018-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0003_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
