# Generated by Django 2.0.7 on 2018-07-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0005_charactertrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('bio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traits', to='rp.Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerseTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('ver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traits', to='rp.Verse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
