# Generated by Django 2.0.7 on 2018-07-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0006_biotrait_versetrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='verses',
            field=models.ManyToManyField(through='rp.Bio', to='rp.Verse'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rp.Character'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rp.Verse'),
        ),
    ]
