# Generated by Django 2.0.7 on 2018-07-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0007_auto_20180713_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bios', to='rp.Character'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bios', to='rp.Verse'),
        ),
    ]
