# Generated by Django 2.0.7 on 2018-07-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0008_auto_20180713_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='verses',
        ),
    ]
