# Generated by Django 2.0.7 on 2018-08-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceclaim',
            name='default_icon',
        ),
        migrations.AddField(
            model_name='icon',
            name='fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='icons', to='icons.FaceClaim'),
        ),
        migrations.AddField(
            model_name='icon',
            name='image',
            field=models.ImageField(default='admin/img/icon-unknown.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=255),
        ),
    ]
