# Generated by Django 2.0.7 on 2018-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_auto_20180806_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='title',
        ),
        migrations.AlterField(
            model_name='icon',
            name='fc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='FaceClaim',
        ),
    ]
