# Generated by Django 2.0.7 on 2018-08-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_auto_20180808_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='fc',
        ),
    ]
